# Generated by Django 5.0.1 on 2024-04-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Users_email',
        ),
    ]
